### ISSUE TITLE
go.field.type not working as intended?

### ISSUE THREAD

**Issue by robfordww** [webrpc/webrpc#127]
This ridl-code:
```
message AlertL
  - alerts: []Alert
    + go.field.type = []AlertDetails

service AppService
  - ListAlerts(limit: int) => (alerts: AlertL)
```
generates the following go-code:
```
type AlertL struct {
	Alerts []*AlertDetails `json:"alerts"`
}
```
I thought it was supposed to result in the the forced "go type" `[]AlertDetails`, but it inserts an extra "`*`" here.   The whole purpose of using the `AlertL `structure was to avoid the "slice of pointers" problem, but that was unsuccessful.

I believe webrpc behaved different in v0.6 with -target=go

`webrpc-gen -schema=./rpc/app.ridl -target=golang -pkg=rpc -server -out=./rpc/app.gen.go`

**Comment by pkieltyka** [comment]
You’re correct, this is a regression @VojtechVitek

**Comment by VojtechVitek** [comment]
Thanks for reporting this. Fixed in github.com/webrpc/gen-golang@v0.7.2.

https://github.com/webrpc/gen-golang/pull/3

**Comment by VojtechVitek** [comment]
FYI, there are more fixes in github.com/webrpc/gen-golang@v0.7.3.

**Comment by pkieltyka** [comment]
FYI, for usage.. you can do:

```
webrpc-gen -schema=api.ridl -target=golang@v0.7.3 -pkg=api -client -server -out=./api.gen.go
```

you can also omit the `@v0.7.3` and it will fetch from the master for templates, however, there is a 1 hour cache of the clone, so passing the version tag is helpful sometimes to be specific. You can also pass -refreshCache to fresh the cache.. but, dont do that every time or you will see you hit github rate limits which is why we have a cache :)
