### ISSUE TITLE
template: types.go.tmpl:29:236: executing "types" at <$input.Meta>: can't evaluate field Meta in type *schema.MethodArgument

### ISSUE THREAD

**Issue by lzap** [webrpc/webrpc#232]
Hello, I just updated to `latest` and getting this error. Version 0.13.0 works fine. So letting you know.

My IDL is here: https://github.com/foresterorg/forester/blob/main/internal/api/ctl/controller.ridl

Love what you doing, cheers.

**Comment by pkieltyka** [comment]
Indeed, looks like v0.13.1 introduced a minor regression, I hit the same issue.

Changes: between v0.13.0 and v0.13.1 https://github.com/webrpc/gen-golang/compare/v0.13.0...v0.13.1

**Comment by VojtechVitek** [comment]
Hi Lukas, thanks for the bug report and for the kind words!

@pkieltyka 
I noticed a similar bug after I merged the golang template support for ridl rpc succinct form. I had an older version of webrpc-gen installed locally and the golang template tried to access a new .Meta field in webrpc schema, which was not defined yet in my webrpc runtime and the template panicked on accessing non-existing field.
I thought I fixed this already but let me look into this again. Looks very similar.

I’m afraid these bugs will be always happening if we keep changing schema.Schema type definition. So in the long term, I’m thinking of
A) marshalling the whole schema into `map[string]any` before sending it to the templates so the templates structs don’t attempt to access non-existing struct field. Maps are safer in Go templates, since you can check for key existence.
B) proper support for template versioning (ie. each template could require a minimal webrpc-gen version)

**Comment by VojtechVitek** [comment]
I think this is the root cause:
https://github.com/webrpc/gen-golang/pull/31/files#r1329823059

Have you tried updating webrpc-gen itself to v0.13.0?

**Comment by lzap** [comment]
I did try to perform `go install github.com/webrpc/webrpc/cmd/webrpc-gen@latest` but without luck. So I did freeze on 0.13.0 for now and I guess for my use, I will be gradually upgrading from time to time not sticking with latest if that makes sense.

Quite honestly, the project works great and you could easily do v1 and start some v2-pre version so people could easily fix their codebase with the CLI tool.

**Comment by VojtechVitek** [comment]
@lzap I can't reproduce the issue on latest webrpc-gen.

```
$ git clone git@github.com:foresterorg/forester.git
Cloning into 'forester'...
remote: Enumerating objects: 658, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 658 (delta 18), reused 27 (delta 9), pack-reused 610
Receiving objects: 100% (658/658), 501.04 KiB | 268.00 KiB/s, done.
Resolving deltas: 100% (351/351), done.
eks-sit1b/hubs-sit1:~/webrpc vojtechvitek@MacBook-Air-4.local 18:54:56

$ cd forester/

$ go install github.com/webrpc/webrpc/cmd/webrpc-gen@latest

$ webrpc-gen --version
webrpc-gen v0.13.0-dev

$ webrpc-gen -silent -schema=internal/api/ctl/controller.ridl -target=golang -pkg=ctl -server -client -out=./internal/api/ctl/proto.gen.go

$ git diff
// <no output>
```

**Comment by pkieltyka** [comment]
maybe something to do with caching? doesn’t make any sense, but its a bit of a phantom bug for me too.. I hit it, and now I’m not experiencing it anymore.

**Comment by lzap** [comment]
Yeah this is weird, I do not see it anymore. I saw it on both my laptop and PC but once I updated to `latest` it is all gone. Feel free to reopen if you hit this again :-D
