### ISSUE TITLE
Add support for map<enum_type, some_other_type>

### ISSUE THREAD

**Issue by c2h5oh** [webrpc/webrpc#44]
Right now only basic types are supported

**Comment by pkieltyka** [comment]
@c2h5oh perhaps the issue is using enum_type as the key. webrpc might right now require string or number as the key, but any value is supported already as you can see in https://github.com/webrpc/webrpc/blob/master/_examples/golang-basics/example.ridl#L46

for enum_type, since its number based, should be pretty easy to add support for it eventually

**Comment by c2h5oh** [comment]
That's exactly what this ticket is about - being able to end up with `map[enumType]valueType` on go side

**Comment by pkieltyka** [comment]
@xiam this would be really nice to add support for too, and should be easy to support in parser since enum's are all numbers under the hood

**Comment by pkieltyka** [comment]
btw, im pretty sure once https://github.com/webrpc/webrpc/issues/55 is solved, then this ticket will be closed along with it

**Comment by VojtechVitek** [comment]
Fixed in https://github.com/webrpc/webrpc/pull/294 🎉
