### ISSUE TITLE
Protofiles or flatbuffers files for schema instead of custom format

### ISSUE THREAD

**Issue by zmitry** [webrpc/webrpc#49]
It might be better to use known format as IDL.

**Comment by pkieltyka** [comment]
Both schemas/formats are designed for binary encoding, as a result, limit the expressiveness of the types. The goal of Webrpc is to handle types native to Web browsers, which is why we use JSON. Plus, RIDL is easier to write and works just as well, requires less tooling and the webrpc-gen is tied to the format to easily write code-generators -- what are some good reasons to adopt protobufs or flatbuffers (would be curious to hear diff pros/cons separately for both since they're different)

**Comment by pkieltyka** [comment]
as well profobuf+grpc combo especially is quite messy in my opinion when it comes to trying to do something custom or making the generator do something custom (ie. its a struggle to support a dynamic hashmap like `map[string]interface{}` with protobuf even with gogoproto or any tooling, and if you want to add annotations / hints to the generators gogoproto helps, but that is just Go specific, it doesn't help for other languages.) All in all, webrpc is far lighter and simpler as it combines all of those needs and designs. The only downside to webrpc is of course we use JSON encoding instead of a super compact binary encoding, but, with code-gen optimization you could write very efficient JSON encoders/decoders, and if you really wanted, could probably figure out a binary format that could work. But the goals of webrpc are for productivity and safety first, and performance second. Although, performance is just fine and onpar with REST apis, and as I mentioned, since we know the schema ahead of time, can be made faster than REST with a number of options. For Web-focused APIs, this isn't an issue. As well, the webrpc responses are a lot more cachable and easy to work with standard http caching. For webapps, I have no reason to use protobufs or flatbuffers but happy to hear some reasons

**Comment by zmitry** [comment]
Okay I just suggest to use proto/flat format but no grpc at all, I thing it's more convenient for new members of the team get used to some idl. And also second reason it's better tooling you have tons of helpers and generators based on proto/flat files.  I'd like to use the tool that have either known format or just regular go files for describing services.

**Comment by pkieltyka** [comment]
hmm yea, not really compelling for my design goals. Thanks for the suggestion tho
